### ISSUE TITLE
Feature request: Add time estimate to NodeMaintenance CRD.

### ISSUE THREAD

**Issue by rohantmp** [kubevirt/node-maintenance-operator#14]
I think it would be useful to have this as an optional field so other operators can decide whether to wait for this node to come back or rebuild their resources elsewhere. I think this would be especially useful for storage because rebuilding storage replicas is a very expensive operation.

**Comment by rohantmp** [comment]
@yanirq

**Comment by yanirq** [comment]
@rohantmp  i agree.  I am planning to start a KEP which will also include possible features in addition to the issues opened here. 
I assume the next version will include more enhancements including CRD expansion.
