### ISSUE TITLE
define and scope relationship to MCO

### ISSUE THREAD

**Issue by cgwalters** [kubevirt/node-maintenance-operator#28]
For OpenShift 4, the [machine-config-operator](https://github.com/openshift/machine-config-operator) is a core part of the platform, and is already handling draining, rebooting etc.  (On the downside, it's not a core part of upstream Kube, so use cases for KubeVirt on upstream Kube would need something else)

Now for 4.3 we plan to add a way to request reboots, and having a CRD for that might be nice.  See: https://github.com/openshift/machine-config-operator/pull/926#issuecomment-515442797

So let's discuss here how to align these.

**Comment by yanirq** [comment]
@cgwalters  First action/question that comes to mind here is if we can move the node-maintenance-operator server side draining functionality to Openshift upstream and consolidate all drain flows.
K8s upstream would be even better - https://github.com/kubernetes/enhancements/pull/1080

**Comment by beekhof** [comment]
@cgwalters are you still interested in a reboot api?
