### ISSUE TITLE
Use a finalizer to untaint the node when the CR is deleted

### ISSUE THREAD

**Issue by rmohr** [kubevirt/node-maintenance-operator#3]
Right now the taints would stay in place after the node is in maintenance. Is it expected to remove the taints independent of the controller, or should they be removed when the CR is deleted?

**Comment by yanirq** [comment]
currently they are removed when the CR is deleted , see:
https://github.com/kubevirt/node-maintenance-operator/blob/fcbc1a4cfdc21eb50b7a4d7de3c264b272538f07/pkg/controller/nodemaintenance/nodemaintenance_controller.go#L191 

ill have to refine that part on the next steps.
