### ISSUE TITLE
Out of band node startup of a shut down node results in it being terminated

### ISSUE THREAD

**Issue by brainfunked** [kubevirt/node-maintenance-operator#44]
I've been able to replicate this with close to a 100% success rate.

* Put a node under maintenance from the dashboard and shut it down.
* Start it up out-of-band, in my case using virsh.
* Node gets terminated automatically.

**Comment by yanirq** [comment]
@brainfunked  please see if this relates to pure NMO , e.g getting this issue with creating NMO CRD with cli.
