### ISSUE TITLE
NMO doesn't detect the node state reliably all the time

### ISSUE THREAD

**Issue by brainfunked** [kubevirt/node-maintenance-operator#45]
I've experienced that NMO doesn't detect the node's status 100% reliably each time. Whether this is for NMO to address or a problem with ironic or its related components, I don't know. Perhaps the issue could be routed appropriately.

In any case, most recent experience was that the node kept showing up as "Shutting Down" or "Powering Up" while it had actually achieved that state. In the latter case, "Powering Up" kept showing up while the node was actually completely offline. In this case, it's possible to experience #44 as well. The screenshots for this mismatch in state are here: https://imgur.com/a/AqNvPLY.

**Comment by yanirq** [comment]
@brainfunked this issue relates to a product using NMO as a component.
closing this issue (a suitable BZ to the related product should be filed in case of need)
