### ISSUE TITLE
Handling out-of-band uncordoning of a node under maintenance

### ISSUE THREAD

**Issue by brainfunked** [kubevirt/node-maintenance-operator#46]
NMO doesn't recognise that a node under maintenance has been cordoned and is no longer in the SchedulingDisabled state. I don't know whether the "Under Maintenance" state must always equate to SchedulingDisabled or not. This needs to be clearly defined.

**Comment by yanirq** [comment]
@brainfunked  this issue relates to a product using NMO as a component.
closing this issue (a suitable BZ to the related product should be filed in case of need)
