### ISSUE TITLE
Patching/Updating a NodeMaintenance CR leaves old node unschedulable

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/node-maintenance-operator#58]
On creation of a NodeMaintenance CR, a specific node becomes unschedulable.
If an existing NodeMaintenance CR is updated and `nodeName` is changed to a different node name, the old node would stay unschedulable after deletion

How to reproduce:
1. Deploy NMO as it states in the main repository page
2. Apply the following NodeMaintenance CR:
```
apiVersion: kubevirt.io/v1alpha1
kind: NodeMaintenance
metadata:
  name: nodemaintenance-xyz
spec:
  nodeName: node02
  reason: "Test node maintenance"
```
3. Check that the node became unschedulable:
```
$ kubectl get nodes
NAME     STATUS                     ROLES    AGE   VERSION
node01   Ready                      master   14m   v1.16.2
node02   Ready,SchedulingDisabled   <none>   14m   v1.16.2
node03   Ready                      <none>   14m   v1.16.2
node04   Ready                      <none>   13m   v1.16.2
```
4. Patch the NodeMaintenance CR and change `nodeName`:
```
$ kubectl patch nodemaintenance nodemaintenance-xyz --type=json -p '[{"op":"replace", "path":"/spec/nodeName", "value":"node03"}]'
```
5. Validate that `node03` is still schedulable:
```
$ kubectl get nodes
NAME     STATUS                     ROLES    AGE   VERSION
node01   Ready                      master   27m   v1.16.2
node02   Ready,SchedulingDisabled   <none>   27m   v1.16.2
node03   Ready                      <none>   27m   v1.16.2
node04   Ready                      <none>   26m   v1.16.2
```
6. Delete the NodeMaintenance CR:
```
$ kubectl delete nodemaintenance nodemaintenance-xyz
nodemaintenance.kubevirt.io "nodemaintenance-xyz" deleted
```
7. Notice that `node02` is still unschedulable:
```
$ kubectl get nodes
NAME     STATUS                     ROLES    AGE   VERSION
node01   Ready                      master   29m   v1.16.2
node02   Ready,SchedulingDisabled   <none>   28m   v1.16.2
node03   Ready                      <none>   28m   v1.16.2
node04   Ready                      <none>   28m   v1.16.2
```

Proposed solution:
Prevent any patches or updates to a NodeMaintenance CR.

**Comment by yanirq** [comment]
> Prevent any patches or updates to a NodeMaintenance CR.

Agreed. there are some other validations that should be added anyway like checking duplicate names and more, but if the general direction is to change NMO to use annotations instead of CR then i wouldn't invest the time on it 
/cc @beekhof

**Comment by beekhof** [comment]
We’re currently working on a webhook to reject CR changes like this

**Comment by slintes** [comment]
/remove-lifecycle rotten

related: #97
