### ISSUE TITLE
Handle CR updates in vaildating webhook

### ISSUE THREAD

**Issue by slintes** [kubevirt/node-maintenance-operator#97]
In #84 an webhook is introduced for validating the creation of nodemaintenance CRs.
We should also validate updates to CRs.

- updates to the nodeName field: should probably be forbidden (are such updates handled at all today?)
- updates to the reason field: should probably be allowed. Check if something needs to be done for handling such updates

wdyt? @beekhof @MoserMichael

**Comment by beekhof** [comment]
Makes sense to me. I don’t think changes to the name are currently handled (since the UI wouldn’t do that) but that’s not an excuse to continue ignoring the problem
